[package]
name = "avocado-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10.2"
prost = "0.12.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"

[build-dependencies]
tonic-build = "0.10.2"
